name: Pull Request

on:
  pull_request:
    branches:
      - '*'

jobs:

  build-and-test:
    uses: ./.github/workflows/base-ci.yml

  diff-coverage-check:
    needs: build-and-test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Pull tests artifacts
        uses: actions/download-artifact@master
        with:
          name: tests-artifacts
          path: tests-artifacts

      - name: Add test results to PR
        uses: EnricoMi/publish-unit-test-result-action@v1
        if: always()
        continue-on-error: true
        with:
          files: "tests-artifacts/**/test-results/**/*.xml"

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Run diff coverage check
        continue-on-error: ${{ contains(github.event.pull_request.labels.*.name, 'ignore-diff-coverage') }}
        run: ./gradlew diffCoverage -Pgithub -PdiffBase="refs/remotes/origin/$GITHUB_BASE_REF"

      - name: Add diff coverage report to PR
        id: jacoco
        uses: madrapps/jacoco-report@v1.2
        if: always()
        continue-on-error: true
        with:
          paths: build/reports/jacoco/diffCoverage/report.xml
          token: ${{ secrets.GITHUB_TOKEN }}
